server:
  port: ${SERVER_PORT:3379}

spring:
  output:
    ansi:
      enabled: never
  mongodb:
    uri: ${MONGODB_URI}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:0}
      timeout: ${REDIS_TIMEOUT:3s}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:3s}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}
  datasource:
    business:
      url: ${BUSINESS_DB_URL}
      username: ${BUSINESS_DB_USERNAME}
      password: ${BUSINESS_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
    playground:
      url: ${PLAYGROUND_DB_URL}
      username: ${PLAYGROUND_DB_USERNAME}
      password: ${PLAYGROUND_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver

application:
  cors:
    enabled: ${CORS_ENABLED:false}
    allowed-origins:
      - ${CORS_ALLOWED_ORIGIN}

rocketmq:
  producer:
    endpoints: ${ROCKETMQ_ENDPOINTS}
    access-key: ${ROCKETMQ_ACCESS_KEY:}
    secret-key: ${ROCKETMQ_SECRET_KEY:}
    namespace: ${ROCKETMQ_NAMESPACE:}
    ssl-enabled: ${ROCKETMQ_SSL_ENABLED:true}

xxl:
  job:
    admin:
      addresses: ${XXL_JOB_ADMIN_ADDRESSES}
      access-token: ${XXL_JOB_ACCESS_TOKEN}
    executor:
      address: ${XXL_JOB_EXECUTOR_ADDRESS}
      port: ${XXL_JOB_EXECUTOR_PORT:19999}
      log-path: ${XXL_JOB_LOG_PATH:/tmp/xxl-job/jobhandler}
