spring:
  application:
    name: xiaoxingxing
  data:
    mongodb:
      auto-index-creation: true
      representation:
        big-decimal: decimal128
  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false

logging:
  level:
    root: INFO
    web: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%-5level) %clr(---){faint} %clr([%15.15thread]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %msg%n"

application:
  mybatis:
    mapper-locations:
      business: []
      playground:
        - "classpath*:mapper/**/*.xml"
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    pagination-db-type: POSTGRE_SQL
  redis:
    lock:
      wait-time: 3s
      lease-time: 10s
      simulated-work-duration: 1s
  cors:
    path-pattern: "/**"
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
  open-api:
    title: API 文档
    version: 1.0.0
    description: 项目接口文档
    group: playground
    display-name: playground

xxl:
  job:
    admin:
      timeout: 3
    executor:
      appname: spring-feature-collection-executor
      ip: ""
      log-retention-days: 7
      excluded-package: org.springframework,spring
