-- V1：创建客户账户基础表，并写入可重复验证的三条学习数据。
-- 迁移由 Flyway 绑定的 playgroundDataSource 执行；不操作 public schema。

CREATE TABLE flyway_migration.customer_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(32) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    total_spent NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_customer_account_customer_code UNIQUE (customer_code),
    CONSTRAINT ck_customer_account_total_spent_non_negative CHECK (total_spent >= 0)
);

COMMENT ON TABLE flyway_migration.customer_account IS 'Flyway 数据库迁移演示用客户账户表';
COMMENT ON COLUMN flyway_migration.customer_account.id IS '客户账户主键';
COMMENT ON COLUMN flyway_migration.customer_account.customer_code IS '客户业务编码';
COMMENT ON COLUMN flyway_migration.customer_account.customer_name IS '客户名称';
COMMENT ON COLUMN flyway_migration.customer_account.total_spent IS '累计消费金额';
COMMENT ON COLUMN flyway_migration.customer_account.created_at IS '账户创建时间';

INSERT INTO flyway_migration.customer_account
    (customer_code, customer_name, total_spent, created_at)
VALUES
    ('CUST-001', '张三', 30000.00, TIMESTAMP '2026-01-01 09:00:00'),
    ('CUST-002', '李四', 10000.00, TIMESTAMP '2026-01-02 09:00:00'),
    ('CUST-003', '王五', 5000.00, TIMESTAMP '2026-01-03 09:00:00');
